services:
  app:
    build:
      context: unknown
      target: app
    container_name: app
    env_file: .env
    environment:
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=8080
      - HTTP_SERVER_PORT=8000
    ports:
      - "8000:8000"  # HTTP 서버
      - "8080:8080"  # WebSocket 서버
    volumes:
      - .env:/var/www/html/.env:ro
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: redis
    env_file:
      - .env.redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "36379:6379"
    volumes:
      - ./redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - .env.postgres
    ports:
      - "35432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

