services:
  game:
    build: .
    image: unknown-game:latest
    container_name: unknown-game
    env_file: .env.game
    ports:
      - "38000:8000" # HTTP 서버
      - "38080:8080" # WebSocket 서버
    depends_on:
      - redis
      - postgres
    networks:
      - default
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: redis
    env_file:
      - .env.redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "36379:6379"
    volumes:
      - unknown_redis:/data
    networks:
      - default
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - .env.postgres
    ports:
      - "35432:5432"
    volumes:
      - unknown_postgres:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    name: melon-net
    external: true

volumes:
  unknown_postgres:
  unknown_redis:
